HCGTV/HCGTV/Areas/User/Controllers/QAController.cs
using HCGTV.Models.Metadata;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Data.Entity;

namespace HCGTV.Areas.User.Controllers
{
    public class QAController : Controller
    {
        Models.TUVIEntities db = new Models.TUVIEntities();
        // GET: User/QA
        public ActionResult Index()
        {
            if (Session["HasVisitedIntro"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var questions = db.LOAIDD
               .Include(x => x.DACDIEM)
               .ToList()
               .Where(x => x.IDLDD < 11)
               .ToList();
            ViewBag.Questions = questions;
            return View();
        }
        [HttpPost]
        public ActionResult LuuLuaChon(string answers)
        {
            string chuoiDapAn = answers;
            int makl; // Biến để lưu mã mệnh
            string prediction; // Biến để lưu mô tả
            string moTa; // Biến để lưu mô tả

                // Tìm luật trùng khớp với chuỗi đáp án
                var luatTrung = db.LUAT
                                 .Where(l => l.NDLUAT == chuoiDapAn)
                                 .FirstOrDefault();

                if (luatTrung != null)
                {
                    // Nếu có luật trùng, lấy mã mệnh tương ứng
                    makl = luatTrung.KETLUAN.MAKL;
                    prediction = db.KETLUAN
                             .Where(m => m.MAKL == makl)
                             .Select(m => m.NDKL)
                             .FirstOrDefault() ?? "Không có dữ liệu"; // Mô tả mặc định nếu không tìm thấy
                    // Lấy mô tả của mệnh từ bảng KETLUAN
                    moTa = db.KETLUAN
                             .Where(m => m.MAKL == makl)
                             .Select(m => m.MOTA)
                             .FirstOrDefault() ?? "Mô tả không có"; // Mô tả mặc định nếu không tìm thấy
                }
                else
                {
                    // Nếu không tìm thấy luật trùng, thiết lập mã mệnh và mô tả mặc định
                    makl = 10;
                    prediction = db.KETLUAN
                             .Where(m => m.MAKL == makl)
                             .Select(m => m.NDKL)
                             .FirstOrDefault() ?? "Không có dữ liệu"; // Mô tả mặc định nếu không tìm thấy
                    moTa = db.KETLUAN
                             .Where(m => m.MAKL == makl)
                             .Select(m => m.MOTA)
                             .FirstOrDefault() ?? "Mô tả không có";// Cập nhật mô tả theo ý muốn
                }

                // Truyền thông tin mã mệnh và mô tả vào view
                ViewBag.Makl = makl;
                ViewBag.NDKL = prediction;
                ViewBag.MoTa = moTa;
                ViewBag.Result = !string.IsNullOrEmpty(chuoiDapAn) && db.LUAT.Any(l => l.NDLUAT == chuoiDapAn);

                // Trả về view KetQua
                return View("KetQua");

        }
        public ActionResult KetQua()
            {
                return View();
            }

        public ActionResult Continue(int? id)
        {
            if (Session["HasVisitedIntro"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            if(id != null)
            {
                var maKL = db.KETLUAN.Where(m => m.MAKL == id).Select(m => m.MAQUYUOC).FirstOrDefault();
                ViewBag.KL = maKL;
            }    
            var questions = db.LOAIDD
               .Include(x => x.DACDIEM)
               .ToList()
               .Where(x => x.IDLDD > 10)
               .ToList();
            ViewBag.Questions = questions;
            return View();
        }

        [HttpPost]
        public ActionResult YourSelected(string answers)
        {
            string chuoiDapAn = answers;
            int makl; // Biến để lưu mã mệnh
            string prediction; // Biến để lưu mô tả
            string moTa; // Biến để lưu mô tả
            // Tìm luật trùng khớp với chuỗi đáp án
            var luatTrung = db.LUAT
                             .Where(l => l.NDLUAT == chuoiDapAn)
                             .FirstOrDefault();

            if (luatTrung != null)
            {
                // Nếu có luật trùng, lấy mã mệnh tương ứng
                makl = luatTrung.KETLUAN.MAKL;
                prediction = db.KETLUAN
                         .Where(m => m.MAKL == makl)
                         .Select(m => m.NDKL)
                         .FirstOrDefault() ?? "Không có dữ liệu"; // Mô tả mặc định nếu không tìm thấy                                                // Lấy mô tả của mệnh từ bảng KETLUAN
                moTa = luatTrung.LOIKHUYEN ?? "Không có"; // Mô tả mặc định nếu không tìm thấy
            }
            else
            {
                // Nếu không tìm thấy luật trùng, thiết lập mã mệnh và mô tả mặc định
                makl = 13;
                prediction = db.KETLUAN
                         .Where(m => m.MAKL == makl)
                         .Select(m => m.NDKL)
                         .FirstOrDefault() ?? "Không có dữ liệu"; // Mô tả mặc định nếu không tìm thấy
                moTa = db.KETLUAN
                         .Where(m => m.MAKL == makl)
                         .Select(m => m.MOTA)
                         .FirstOrDefault() ?? "Mô tả không có";// Cập nhật mô tả theo ý muốn
            }

            // Truyền thông tin mã mệnh và mô tả vào view
            ViewBag.Makl = makl;
            ViewBag.NDKL = prediction;
            ViewBag.MoTa = moTa;
            ViewBag.Result = !string.IsNullOrEmpty(chuoiDapAn) && db.LUAT.Any(l => l.NDLUAT == chuoiDapAn);

            // Trả về view Ket Qua
            return View("Lastresult");

        }
        public ActionResult Lastresult()
        {
            return View();
        }

    }
}

HCGTV/HCGTV/Areas/User/Views/QA/Continue.cshtml
@{
    ViewBag.Title = "Dự đoán sự nghiệp";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en"
      class="light-style layout-wide customizer-hide"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path=""
      data-template="vertical-menu-template-free">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
    <title>Dự đoán sự nghiệp</title>
    <meta name="description" content="" />
    <link rel="icon" type="image/x-icon" href="~/Assets/User/img/jollibee1.ico" />
    <link rel="stylesheet" href="~/Assets/User/css/Questions.css" />
    <script src="https://kit.fontawesome.com/6b8a71fb94.js" crossorigin="anonymous"></script>
</head>
<body>
    <div id="loading" class="loading-overlay" style="display:none;">
        <div class="spinner"></div>
    </div>
    <h2 style="text-align: center; font-size: 2.2rem; margin-top: 20px; margin-bottom: 10px; font-family: math;">Hãy trả lời các câu hỏi sau</h2>
    <a href="/User/Home/Index" class="stop-ques"><i class="fa-solid fa-right-from-bracket"></i>Exit</a>
    <div id="quiz">
        @{
            var questions = ViewBag.Questions as List<HCGTV.Models.LOAIDD>; // Chuyển đổi ViewBag thành danh sách
        }

        @if (questions != null)
        {
            for (int i = 0; i < questions.Count; i++)
            {
                <div class="slide" id="slide-@i" style="display: @(i == 0 ? "block" : "none")">
                    <h3 style=" text-align: center; font-size: 1.5rem; font-family: math; margin-bottom: 10px;">@questions[i].NOIDUNG</h3> <!-- Hiển thị tên câu hỏi -->
                    <span class="note-text">*Hãy trả lời hết các câu hỏi để nhận được dự đoán</span>
                    <form class="slide-items">
                        @foreach (var item in questions[i].DACDIEM) // Hiển thị đáp án
                        {
                            <input type="radio" id="@item.IDDD" name="answer-@i" value="@item.MAQUYUOC" />
                            <label for="@item.IDDD" class="slide-item">@item.NDMOTA </label>
                            <br />
                        }
                    </form>
                    <button type="button" class="next" onclick="nextSlide(@i)" @(i == questions.Count - 1 ? "disabled" : "")>Next</button>
                    <button type="button" class="prev" onclick="prevSlide(@i)" @(i == 0 ? "disabled" : "")>Previous</button>
                </div>
            }
            <button id="finish" class="predict" style="display: none" onclick="finish()">Hoàn tất</button>
        }
        else
        {
            <p>Không có câu hỏi nào.</p>
        }
    </div>

    <script>
    let currentSlide = 0;

    function nextSlide(i) {
        document.getElementById(`slide-${i}`).style.display = 'none';
        currentSlide++;
        document.getElementById(`slide-${currentSlide}`).style.display = 'block';
        document.getElementById('finish').style.display = currentSlide === @ViewBag.Questions.Count - 1 ? 'block' : 'none';
    }

    function prevSlide(i) {
        document.getElementById(`slide-${i}`).style.display = 'none';
        currentSlide--;
        document.getElementById(`slide-${currentSlide}`).style.display = 'block';
        document.getElementById('finish').style.display = currentSlide === @ViewBag.Questions.Count - 1 ? 'block' : 'none';
    }
    function finish() {
        let answers = '@ViewBag.KL.ToString()' + '^';
        for (let i = 0; i < @ViewBag.Questions.Count; i++) {
            let answer = document.querySelector(`input[name="answer-${i}"]:checked`);
            if (answer) {
                answers += answer.value + '^';
            }
        }
        console.log(answers);
        if (!answers || answers.length<13) {
            alert("Vui lòng trả lời các câu hỏi.");
            return; // Dừng thực hiện hàm nếu không đủ dữ liệu
        }
        answers = answers.slice(0, -1); // Xóa ký tự cuối cùng

        // Gửi chuỗi đáp án đến server
        fetch('@Url.Action("YourSelected", "QA")', {
            method: 'POST',
            body: JSON.stringify({ answers: answers }),
            headers: {
                'Content-Type': 'application/json'
            }
        }).then(response => {
            return response.text();
        }).then(data => {
            document.getElementById('loading').style.display = 'flex';
            setTimeout(function () {
                document.body.innerHTML = data; // Hiển thị kết quả
            }, 1000);
        });
        }
    </script>
    <style>
        #loading {
            display: none; /* Ban đầu ẩn spinner */
            position: fixed;
            width: 100vw;
            height: 100vh;
            background-color: rgba(0, 0, 0, 0.5); /* Nền mờ */
            z-index: 9999;
            top: 0;
            left: 0;
            justify-content: center;
            align-items: center;
            display: flex;
        }

        .spinner {
            border: 8px solid #f3f3f3;
            border-top: 8px solid #3498db;
            border-radius: 50%;
            width: 60px;
            height: 60px;
            animation: spin 1s linear infinite;
        }

        @@keyframes spin {
            0% {
                transform: rotate(0deg);
            }

            100% {
                transform: rotate(360deg);
            }
        }
    </style>
</body>
</html>  

HCGTV/HCGTV/Areas/User/Views/QA/Index.cshtml
@{
    ViewBag.Title = "Câu Hỏi Tử Vi";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en"
      class="light-style layout-wide customizer-hide"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path=""
      data-template="vertical-menu-template-free">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
    <title>Dự đoán số mệnh</title>
    <meta name="description" content="" />
    <link rel="icon" type="image/x-icon" href="~/Assets/User/img/jollibee1.ico" />
    <link rel="stylesheet" href="~/Assets/User/css/Questions.css" />
    <script src="https://kit.fontawesome.com/6b8a71fb94.js" crossorigin="anonymous"></script>
</head>
<body>
    <div id="loading" class="loading-overlay" style="display:none;">
        <div class="spinner"></div>
    </div>
    <h2 style="text-align: center; font-size: 2.2rem; margin-top: 20px; margin-bottom: 10px; font-family: math;">Hãy trả lời các câu hỏi sau</h2>
    <a href="/User/Home/Index" class="stop-ques"><i class="fa-solid fa-right-from-bracket"></i>Exit</a>
    <div id="quiz">
        @{
            var questions = ViewBag.Questions as List<HCGTV.Models.LOAIDD>; // Chuyển đổi ViewBag thành danh sách
        }

        @if (questions != null)
        {
            for (int i = 0; i < questions.Count; i++)
            {
                <div class="slide" id="slide-@i" style="display: @(i == 0 ? "block" : "none")">
                    <h3 style=" text-align: center; font-size: 1.5rem; font-family: math; margin-bottom: 10px;">@questions[i].NOIDUNG</h3> <!-- Hiển thị tên câu hỏi -->
                    <span class="note-text">*Bạn có thể bỏ qua một số câu nếu không có đáp án phù hợp</span>
                    <form class="slide-items">
                        @foreach (var item in questions[i].DACDIEM) // Hiển thị đáp án
                        {
                            <input type="radio" id="@item.IDDD" name="answer-@i" value="@item.MAQUYUOC" />
                            <label for="@item.IDDD" class="slide-item">@item.NDMOTA </label>
                            <br />
                        }
                    </form>
                    <button type="button" class="next" onclick="nextSlide(@i)" @(i == questions.Count - 1 ? "disabled" : "")>Next</button>
                    <button type="button" class="prev" onclick="prevSlide(@i)" @(i == 0 ? "disabled" : "")>Previous</button>
                </div>
            }
            <button id="finish" class="predict" style="display: none" onclick="finish()">Hoàn tất</button>
        }
        else
        {
            <p>Không có câu hỏi nào.</p>
        }
    </div>

    <script>
    let currentSlide = 0;

    function nextSlide(i) {
        document.getElementById(`slide-${i}`).style.display = 'none';
        currentSlide++;
        document.getElementById(`slide-${currentSlide}`).style.display = 'block';
        document.getElementById('finish').style.display = currentSlide === @ViewBag.Questions.Count - 1 ? 'block' : 'none';
    }

    function prevSlide(i) {
        document.getElementById(`slide-${i}`).style.display = 'none';
        currentSlide--;
        document.getElementById(`slide-${currentSlide}`).style.display = 'block';
        document.getElementById('finish').style.display = currentSlide === @ViewBag.Questions.Count - 1 ? 'block' : 'none';
    }
        let lastChecked = null;

        document.querySelectorAll('input[name^="answer-"]').forEach(function (radio) {
            radio.addEventListener('click', function (e) {
                if (lastChecked === this) {
                    this.checked = false;
                    lastChecked = null; 
                } else {
                    lastChecked = this;
                }
            });
        });

    function finish() {
        let answers = '';
        for (let i = 0; i < @ViewBag.Questions.Count; i++) {
            let answer = document.querySelector(`input[name="answer-${i}"]:checked`);
            if (answer) {
                answers += answer.value + '^';
            }
        }
        console.log(answers);
        if (!answers || answers.length < 12) {
            alert("Không đủ dữ liệu để dự đoán. Vui lòng trả lời tối thiểu 4 câu hỏi.");
            return; // Dừng thực hiện hàm nếu không đủ dữ liệu
        }

        answers = answers.slice(0, -1); // Xóa ký tự cuối cùng

        // Gửi chuỗi đáp án đến server
        fetch('@Url.Action("LuuLuaChon", "QA")', {
            method: 'POST',
            body: JSON.stringify({ answers: answers }),
            headers: {
                'Content-Type': 'application/json'
            }
        }).then(response => {
            return response.text();
        }).then(data => {
            document.getElementById('loading').style.display = 'flex';
            setTimeout(function () {
                document.body.innerHTML = data; // Hiển thị kết quả
            }, 1000); 
        });
        }
    </script>
    <style>
        #loading {
            display: none; /* Ban đầu ẩn spinner */
            position: fixed;
            width: 100vw;
            height: 100vh;
            background-color: rgba(0, 0, 0, 0.5); /* Nền mờ */
            z-index: 9999;
            top: 0;
            left: 0;
            justify-content: center;
            align-items: center;
            display: flex;
        }

        .spinner {
            border: 8px solid #f3f3f3;
            border-top: 8px solid #3498db;
            border-radius: 50%;
            width: 60px;
            height: 60px;
            animation: spin 1s linear infinite;
        }

        @@keyframes spin {
            0% {
                transform: rotate(0deg);
            }

            100% {
                transform: rotate(360deg);
            }
        }
    </style>
</body>
</html>

HCGTV/HCGTV/Areas/User/Views/QA/KetQua.cshtml
@{
    ViewBag.Title = "KetQua";
    Layout = null;
}

@{
    int makl = ViewBag.Makl; // Nhận mã mệnh từ ViewBag
    string prediction = ViewBag.NDKL;
    string moTa = ViewBag.MoTa; // Nhận mô tả từ ViewBag
    bool result = ViewBag.Result; // Nhận giá trị result từ ViewBag
    string message = ViewBag.Message; // Nhận thông báo từ ViewBag
}
<!DOCTYPE html>
<html lang="en"
      class="light-style layout-wide customizer-hide"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path=""
      data-template="vertical-menu-template-free">
<head>
    <title>Kết quả dự đoán số mệnh</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
    <h2 style="text-align: center; font-size: 2.2rem; margin-top: 20px; margin-bottom: 10px; font-family: math;">Kết quả dự đoán</h2>
    <div id="floatingModal" class="floating-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                @if (result) // Nếu có luật trùng
                {
                    <div class="modal-header">
                        <div class="icon-box">
                            <i class="material-icons">&#xE876;</i>
                        </div>
                        <h4 class="modal-title w-100" style="color: #41c306;">Bạn là người có @prediction</h4>
                    </div>
                    <div class="modal-body">
                        <p class="text-center" style="font-size: 18px; color: #0029f0; font-style: italic; font-family: math; margin: 0;">@moTa</p>
                    </div>
                }
                else // Nếu không có chuỗi đáp án
                {
                    <div class="modal-header">
                        <div class="icon-box">
                            <i class="material-icons">&#xE876;</i>
                        </div>
                        <h4 class="modal-title w-100" style="color: #41c306;">Bạn là người có @prediction</h4>
                    </div>
                    <div class="modal-body">
                        <p class="text-center" style="font-size: 18px; color: #0029f0; font-style: italic; font-family: math;margin:0;">@moTa</p>
                    </div>
                }
            <div class="modal-footer">
                <a href="/User/Home/Index" class="btn" style=" padding: 8px; font-size: 1.2rem; font-family: cursive;">Stop</a>
                <a href="@Url.Action("Continue", "QA",new { id = makl })" class="btn" onclick ="redirect()"style=" padding: 8px; font-size: 1.2rem; font-family: cursive;">Continue</a>
            </div>
            </div>
        </div>
    </div>
    <script>
        function redirect() {
            document.getElementById('loading').style.display = 'none';
        }
    </script>
    <style>
        .floating-modal {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -65%);
            background-color: rgb(255 255 255 / 56%);
            border-radius: 5px;
            box-shadow: 0px 2px 2px 5px rgb(255 255 255 / 39%);
            z-index: 1000;
            padding: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
            border: 1px solid rgba(0, 0, 0, .2);
        }

        .modal-content {
            background-color: rgb(255 255 255 / 56%);
        }

        .modal-header {
            border-bottom: none;
            position: relative;
            width: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
        }

            .modal-header .icon-box {
                color: #fff;
                position: absolute;
                top: -30px;
                width: 60px;
                height: 60px;
                border-radius: 50%;
                background: #82ce34;
                padding: 10px;
                text-align: center;
                box-shadow: 0px 2px 2px 2px rgba(0, 0, 0, 0.1);
                display: flex;
                justify-content: center;
                align-items: center;
            }

                .modal-header .icon-box i {
                    font-size: 36px;
                }

        .modal-title {
            margin: 0;
            font-size: 30px;
            color: #636677;
            text-align: center;
            margin-top: 20px;
        }

        .modal-body,
        .modal-footer {
            border: none;
            text-align: center;
            border-radius: 5px;
            font-size: 13px;
            width: 100%;
        }

            .modal-footer .btn {
                color: #fff;
                border-radius: 4px;
                background: #82ce34;
                text-decoration: none;
                transition: all 0.4s;
                line-height: normal;
                border: none;
                width: 100%;
                margin-top: 10px;
            }

                .modal-footer .btn:hover,
                .modal-footer .btn:focus {
                    background: #6fb32b;
                    outline: none;
                }

        .modal-footer {
            flex-wrap: nowrap;
        }

        .hidden-modal {
            display: none !important;
        }
    </style>
</body>
</html>

HCGTV/HCGTV/Areas/User/Views/QA/Lastresult.cshtml
@{
    ViewBag.Title = "Lastresult"; 
    Layout = null;
}

@{
    int makl = ViewBag.Makl; // Nhận mã mệnh từ ViewBag
    string prediction = ViewBag.NDKL;
    string moTa = ViewBag.MoTa; // Nhận mô tả từ ViewBag
    bool result = ViewBag.Result; // Nhận giá trị result từ ViewBag
    string message = ViewBag.Message; // Nhận thông báo từ ViewBag
}
<!DOCTYPE html>
<html lang="en"
      class="light-style layout-wide customizer-hide"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path=""
      data-template="vertical-menu-template-free">
<head>
    <title>Kêt quả dự đoán sự nghiệp</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
    <h2 style="text-align: center; font-size: 2.2rem; margin-top: 20px; margin-bottom: 10px; font-family: math;">Kết quả dự đoán</h2>
    <div id="floatingModal" class="floating-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                @if (result) // Nếu có luật trùng
                {
                    <div class="modal-header">
                        <div class="icon-box">
                            <i class="material-icons">&#xE876;</i>
                        </div>
                        <h4 class="modal-title w-100" style="color: #41c306;">Con đường sự nghiệp của bạn sẽ @prediction</h4>
                    </div>
                    <div class="modal-body">
                        <p class="text-center" style="font-size: 18px; color: #0029f0; font-style: italic; font-family: math;margin:0;">@moTa</p>
                    </div>
                }
                else // Nếu không có chuỗi đáp án
                {
                    <div class="modal-header">
                        <div class="icon-box">
                            <i class="material-icons">&#xE876;</i>
                        </div>
                        <h4 class="modal-title w-100" style="color: #41c306;">Con đường sự nghiệp của bạn sẽ @prediction</h4>
                    </div>
                    <div class="modal-body">
                        <p class="text-center" style="font-size: 18px; color: #0029f0; font-style: italic; font-family: math; margin: 0;">@moTa</p>
                    </div>
                }
                <div class="modal-footer">
                    <a href="/User/Home/Index" class="btn" style=" padding: 8px; font-size: 1.2rem; font-family: cursive;">Start Again</a>
                </div>
            </div>
        </div>
    </div>

    <style>
        .floating-modal {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -65%);
            background-color: rgb(255 255 255 / 56%);
            border-radius: 5px;
            box-shadow: 0px 2px 2px 5px rgb(255 255 255 / 39%);
            z-index: 1000;
            padding: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
            border: 1px solid rgba(0, 0, 0, .2);
        }

        .modal-content {
            background-color: rgb(255 255 255 / 56%);
        }

        .modal-header {
            border-bottom: none;
            position: relative;
            width: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
        }

            .modal-header .icon-box {
                color: #fff;
                position: absolute;
                top: -30px;
                width: 60px;
                height: 60px;
                border-radius: 50%;
                background: #82ce34;
                padding: 10px;
                text-align: center;
                box-shadow: 0px 2px 2px 2px rgba(0, 0, 0, 0.1);
                display: flex;
                justify-content: center;
                align-items: center;
            }

                .modal-header .icon-box i {
                    font-size: 36px;
                }

        .modal-title {
            margin: 0;
            font-size: 30px;
            color: #636677;
            text-align: center;
            margin-top: 20px;
        }

        .modal-body,
        .modal-footer {
            border: none;
            text-align: center;
            border-radius: 5px;
            font-size: 13px;
            width: 100%;
        }

            .modal-footer .btn {
                color: #fff;
                border-radius: 4px;
                background: #82ce34;
                text-decoration: none;
                transition: all 0.4s;
                line-height: normal;
                border: none;
                width: 100%;
                margin-top: 10px;
            }

                .modal-footer .btn:hover,
                .modal-footer .btn:focus {
                    background: #6fb32b;
                    outline: none;
                }

        .modal-footer {
            flex-wrap: nowrap;
        }

        .hidden-modal {
            display: none !important;
        }
    </style>
</body>
</html>